# Generated by Django 3.1.7 on 2021-12-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Floodlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FluorescentTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HandDryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_name', models.CharField(max_length=100)),
                ('meter_location', models.CharField(max_length=100)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weekly_consumption', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Photocopier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveBigIntegerField()),
                ('daily_cost', models.PositiveBigIntegerField()),
            ],
        ),
    ]
