# Generated by Django 3.1.7 on 2021-12-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_weeklyconsumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyConsumption',
        ),
    ]
