# Generated by Django 3.1.7 on 2021-12-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_weeklyconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_location', models.CharField(max_length=100)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meter2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_location', models.CharField(max_length=100)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meter3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meter_location', models.CharField(max_length=100)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='meter_name',
        ),
    ]
