# Generated by Django 3.1.7 on 2022-01-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211231_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='printer',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
