# Generated by Django 3.1.7 on 2022-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220102_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplifier',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='computers',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='floodlight',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fluorescenttube',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='handdryer',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='photocopier',
            name='daily_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='printer',
            name='hours_used',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
