# Generated by Django 3.1.7 on 2022-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220102_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter1',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meter1',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meter2',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meter2',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meter3',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meter3',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
