# Generated by Django 3.1.7 on 2022-01-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220102_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='amplifier',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computers',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floodlight',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluorescenttube',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handdryer',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photocopier',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='printer',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
