# Generated by Django 3.1.7 on 2022-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('year_2017', models.CharField(max_length=100)),
                ('year_2018', models.CharField(max_length=100)),
                ('year_2021', models.CharField(max_length=100)),
            ],
        ),
    ]
