# Generated by Django 3.1.7 on 2022-03-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20220221_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowmeter',
            old_name='consumption',
            new_name='average_reading',
        ),
        migrations.RenameField(
            model_name='flowmeter',
            old_name='daily_cost',
            new_name='reading1',
        ),
        migrations.RemoveField(
            model_name='flowmeter',
            name='hours_used',
        ),
        migrations.AddField(
            model_name='flowmeter',
            name='reading2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
